services:
  app:
    image: otcheredev/sosbackend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AGORA_CERTIFICATE=${AGORA_CERTIFICATE}
      - AGORA_ID=${AGORA_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE_ACCESS_TOKEN=${HUGGING_FACE_ACCESS_TOKEN}
      - AWS_ACCESS_KEY_ID1=${AWS_ACCESS_KEY_ID1}
      - AWS_SECRET_ACCESS_KEY1=${AWS_SECRET_ACCESS_KEY1}
      - MONGO_URI=${MONGO_URI}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUDNAME=${CLOUDINARY_CLOUDNAME}
      - APP_ID=${APP_ID}
      - JWT_SECRET=${JWT_SECRET}

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
